//! Opaque, stable, filesystem-safe identifiers for Root work objects.
//!
//! IDs are ULID-based and namespaced with a stable Root prefix so that the
//! object type is readable without a lookup. They are independent of the
//! repository directory name and safe to use as filesystem path components.

use ulid::Ulid;

pub const WORKSPACE_PREFIX: &str = "root_ws";
pub const GOAL_PREFIX: &str = "root_goal";
pub const SESSION_PREFIX: &str = "root_sess";
pub const DECISION_PREFIX: &str = "root_dec";
pub const FINDING_PREFIX: &str = "root_find";
pub const ARTIFACT_PREFIX: &str = "root_art";
pub const CHECKPOINT_PREFIX: &str = "root_cp";
pub const PROVENANCE_PREFIX: &str = "root_prov";
pub const EVENT_PREFIX: &str = "root_evt";
pub const HANDOFF_PREFIX: &str = "root_handoff";

fn generate(prefix: &str) -> String {
    format!("{}_{}", prefix, Ulid::new())
}

pub fn workspace_id() -> String {
    generate(WORKSPACE_PREFIX)
}

pub fn goal_id() -> String {
    generate(GOAL_PREFIX)
}

pub fn session_id() -> String {
    generate(SESSION_PREFIX)
}

pub fn decision_id() -> String {
    generate(DECISION_PREFIX)
}

pub fn finding_id() -> String {
    generate(FINDING_PREFIX)
}

pub fn artifact_id() -> String {
    generate(ARTIFACT_PREFIX)
}

pub fn checkpoint_id() -> String {
    generate(CHECKPOINT_PREFIX)
}

pub fn provenance_id() -> String {
    generate(PROVENANCE_PREFIX)
}

pub fn event_id() -> String {
    generate(EVENT_PREFIX)
}

pub fn handoff_id() -> String {
    generate(HANDOFF_PREFIX)
}

/// Returns true when `id` carries `prefix` and has a valid ULID body.
pub fn is_valid_id(prefix: &str, id: &str) -> bool {
    match id.strip_prefix(&format!("{}_", prefix)) {
        Some(body) => !body.is_empty() && Ulid::from_string(body).is_ok(),
        None => false,
    }
}

/// Returns true when `id` is a workspace ID generated by Root.
pub fn is_valid_workspace_id(id: &str) -> bool {
    is_valid_id(WORKSPACE_PREFIX, id)
}

/// IDs must be usable directly as a single filesystem path component.
pub fn is_filesystem_safe(id: &str) -> bool {
    !id.is_empty()
        && id
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
}
